[package]
name = "guessing-game"
version = "0.1.0"
authors = ["elie-rbr elise.reber.2001@gmail.com"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
